---

name: Daily Build (ARM)

on:
  push:
    branches:
      - master
      - github-update
  workflow_dispatch: {}

jobs:
  build:
    name: Build Arm
    runs-on: ubuntu-20.04

    steps:
      - name: Clean
        uses: easimon/maximize-build-space@v7
        with:
          root-reserve-mb: 20480
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo ./build-rpi.sh

      # - name: Save ISO
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: elementaryos-arm64
      #     path: elementaryos-arm64.iso
